language: node_js
node_js: '10'

script:
  - yarn test
  - yarn build
  - mv build build-success
  - git checkout buggy-implementation
  - yarn install
  - yarn build
  - mv build bug
  - mv build-success build
  - mv bug build/

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  target-branch: gh-pages
  local-dir: build
  on:
    branch: master
