language: node_js
node_js: '10'

script:
  - yarn test
  - yarn build
  - git clone https://github.com/dubzzz/connect-four-react.git
  - cd connect-four-react
  - git checkout buggy-implementation
  - yarn install
  - yarn build
  - cd ..
  - mv connect-four-react/build build/bug

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  target-branch: gh-pages
  local-dir: build
  on:
    branch: master
